apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - monitoring/gatus/public
  - monitoring/gatus/gatus-alerting-sealed-secret.yaml

patchesStrategicMerge:
  - cert-manager-email-patch.yaml

commonLabels:
  environment: production
