---
apiVersion: v1
kind: Service
metadata:
  name: homepage-api
spec:
  selector:
    app: homepage
    component: backend
  ports:
  - port: 3000
    targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: homepage-frontend
spec:
  selector:
    app: homepage
    component: frontend
  ports:
  - port: 80
    targetPort: 80
