---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homepage-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - pseudolab-devfactory.com
    - www.pseudolab-devfactory.com
    secretName: homepage-tls
  rules:
  - host: pseudolab-devfactory.com
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: homepage-api
            port:
              number: 3000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: homepage-frontend
            port:
              number: 80
  - host: www.pseudolab-devfactory.com
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: homepage-api
            port:
              number: 3000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: homepage-frontend
            port:
              number: 80
