apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps-homepage

resources:
  - ../../base
  - namespace.yaml
  - ingress.yaml
  - sealed-secret.yaml

commonLabels:
  environment: production
  project: devfactory-homepage

images:
  - name: ghcr.io/pseudo-lab/devfactory-homepage-backend
    newTag: sha-placeholder # Dynamically updated by CI (GitHub SHA)
  - name: ghcr.io/pseudo-lab/devfactory-homepage-frontend
    newTag: sha-placeholder # Dynamically updated by CI (GitHub SHA)
