apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # - gatus/public/manifests.yaml
  # - gatus/admin/manifests.yaml
  - victoria-metrics/grafana-admin-sealed-secret.yaml
  - victoria-metrics/alertmanager-config-sealed-secret.yaml
